name: Auto Create and Approve PR

on:
  push:
    branches:
      - main # Branch de origem

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Fetch all branches
      run: git fetch --all

    - name: Create Pull Request
      id: create_pr
      run: |
        # Utilizando a GitHub CLI para criar o PR
        gh pr create --base homolog --head main --title "Auto Merge: main -> homolog" --body "Merge automático de main para homolog."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Approve and Merge Pull Request
      id: merge_pr
      run: |
        # Extrair o número do PR criado
        PR_NUMBER=$(gh pr list --state open --head main --base homolog --json number -q '.[0].number')

        # Mesclar o PR
        gh pr merge $PR_NUMBER --squash --admin --delete-branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
